### ISSUE TITLE
Is it ok with only heating PAC ?

### ISSUE THREAD

**Issue by L0nhed** [dricair/daikin-to-jeedom#1]
Dear @dricair ,

In first thank you for you great job but I have some problem with this error code :

```
root@raspberrypi3:/root/daikin-to-jeedom# python3 daikin_to_jeedom.py -v
2023-11-04 02:52:24      DEBUG: Reading configuration file conf.json
2023-11-04 02:52:24      DEBUG: Daikin - Executing script daikin_data.js
Traceback (most recent call last):
  File "daikin_to_jeedom.py", line 269, in <module>
    consumption_data = data["climateControl"]["consumptionData"]["/electrical"]
KeyError: 'climateControl'
```

Have you already see this error ?
I have heating PAC Daikin altherma 3 H W, have you try tris code only with heating/cooling air conditioner ?

NB: I post in first time on jeedom community : https://community.jeedom.com/t/daikin-onecta-ajout-de-la-consommation/108866

Thank you in advance for your reply.
Best regards

**Comment by dricair** [comment]
Hi

I did only test it with the PAC I have. However if you post one of the JSON
files that is saved in daikin-data directory, I can have a look and see if
it can be adapted.

Regards
Cedric

**Comment by L0nhed** [comment]
Dear @dricair ,

Please see json file attach (I removed some private information on this file) :
[logs.json](https://github.com/dricair/daikin-to-jeedom/files/13328672/logs.json)

Thank you for your help.
Best regards

**Comment by dricair** [comment]
The structure of the file is different. I added a function to adapt to different type of files. Could you verify it fixes the issue you have been seeing, if not you can reopen.

**Comment by L0nhed** [comment]
Dear @dricair ,
Thank you for your quick fix.
I tried with your new code and good news I no longer have any errors:

```
root@raspberrypi3Domo:/root/daikin-to-jeedom# python3 daikin_to_jeedom.py -v
2023-11-12 10:36:16      DEBUG: Reading configuration file conf.json
2023-11-12 10:36:16      DEBUG: Daikin - Executing script daikin_data.js
root@raspberrypi3Domo:/root/daikin-to-jeedom#
```

But nothing is written in "daikin-data" folder :

```
root@raspberrypi3Domo:/root/daikin-to-jeedom# ll daikin-data
total 0
```


Thank you again for your help.
Best regards

**Comment by L0nhed** [comment]
Edit: I restart an "npm install" and then it seems to progress :

```
root@raspberrypi3Domo:/root/daikin-to-jeedom# npm install

added 82 packages, and audited 83 packages in 32s

22 packages are looking for funding
  run `npm fund` for details

3 vulnerabilities (2 low, 1 high)

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```

I retry :

```
root@raspberrypi3Domo:/root/daikin-to-jeedom# python3 daikin_to_jeedom.py -v
2023-11-12 10:45:22      DEBUG: Reading configuration file conf.json
2023-11-12 10:45:22      DEBUG: Daikin - Executing script daikin_data.js
2023-11-12 10:45:28      DEBUG: Starting new HTTP connection (1): 127.0.0.1:80
2023-11-12 10:45:28      DEBUG: http://127.0.0.1:80 "GET /core/api/jeeApi.php?apikey=--retiré--&type=variable&name=daikin.--retiré--.commit_date HTTP/1.1" 200 0
2023-11-12 10:45:28      DEBUG: Conversion of value '' failed, using default '1970-01-01 01:00:00'
2023-11-12 10:45:28      DEBUG: Jeedom - read variable daikin.--retiré--.commit_date --> 1970-01-01 01:00:00
2023-11-12 10:45:28      DEBUG: Starting new HTTP connection (1): 127.0.0.1:80
2023-11-12 10:45:28      DEBUG: http://127.0.0.1:80 "GET /core/api/jeeApi.php?apikey=--retiré--&type=variable&name=daikin.--retiré--.cooling_current HTTP/1.1" 200 0
2023-11-12 10:45:28      DEBUG: Conversion of value '' failed, using default '0'
2023-11-12 10:45:28      DEBUG: Jeedom - read variable daikin.--retiré--.cooling_current --> 0
2023-11-12 10:45:28      DEBUG: Starting new HTTP connection (1): 127.0.0.1:80
2023-11-12 10:45:28      DEBUG: http://127.0.0.1:80 "GET /core/api/jeeApi.php?apikey=--retiré--&type=variable&name=daikin.--retiré--.cooling_commit HTTP/1.1" 200 0
2023-11-12 10:45:28      DEBUG: Conversion of value '' failed, using default '0'
2023-11-12 10:45:28      DEBUG: Jeedom - read variable daikin.--retiré--.cooling_commit --> 0
2023-11-12 10:45:28      DEBUG: Starting new HTTP connection (1): 127.0.0.1:80
2023-11-12 10:45:28      DEBUG: http://127.0.0.1:80 "GET /core/api/jeeApi.php?apikey=--retiré--&type=variable&name=daikin.--retiré--.heating_current HTTP/1.1" 200 0
2023-11-12 10:45:28      DEBUG: Conversion of value '' failed, using default '0'
2023-11-12 10:45:28      DEBUG: Jeedom - read variable daikin.--retiré--.heating_current --> 0
2023-11-12 10:45:28      DEBUG: Starting new HTTP connection (1): 127.0.0.1:80
2023-11-12 10:45:28      DEBUG: http://127.0.0.1:80 "GET /core/api/jeeApi.php?apikey=--retiré--&type=variable&name=daikin.--retiré--.heating_commit HTTP/1.1" 200 0
2023-11-12 10:45:28      DEBUG: Conversion of value '' failed, using default '0'
2023-11-12 10:45:28      DEBUG: Jeedom - read variable daikin.--retiré--.heating_commit --> 0
2023-11-12 10:45:28      DEBUG: --retiré-- - commit_date: 1970-01-01 01:00:00, cooling_current: 0, cooling_commit: 0, heating_current: 0, heating_commit: 0
Traceback (most recent call last):
  File "daikin_to_jeedom.py", line 320, in <module>
    cooling_update = cumulate_power(consumption_data["cooling"]["d"], values["commit_date"], now)
KeyError: 'cooling'
```

It's seem another problem

Thank you again for your help.
Best regards

**Comment by dricair** [comment]
Yes I forgot to check if there is cooling data inside the file. It should be solved now.

**Comment by L0nhed** [comment]
Dear @dricair ,

I'm going to bother you again but there still seems to be another problem :/  

```
root@raspberrypi3Domo:/root/daikin-to-jeedom# python3 daikin_to_jeedom.py -v
2023-11-14 09:51:23      DEBUG: Reading configuration file conf.json
2023-11-14 09:51:23      DEBUG: Daikin - Executing script daikin_data.js
2023-11-14 09:51:28      DEBUG: Starting new HTTP connection (1): 127.0.0.1:80
2023-11-14 09:51:29      DEBUG: http://127.0.0.1:80 "GET /core/api/jeeApi.php?apikey=--retiré--&type=variable&name=daikin.--retiré--.commit_date HTTP/1.1" 200 0
2023-11-14 09:51:29      DEBUG: Conversion of value '' failed, using default '1970-01-01 01:00:00'
2023-11-14 09:51:29      DEBUG: Jeedom - read variable daikin.--retiré--.commit_date --> 1970-01-01 01:00:00
2023-11-14 09:51:29      DEBUG: Starting new HTTP connection (1): 127.0.0.1:80
2023-11-14 09:51:29      DEBUG: http://127.0.0.1:80 "GET /core/api/jeeApi.php?apikey=--retiré--&type=variable&name=daikin.--retiré--.heating_current HTTP/1.1" 200 0
2023-11-14 09:51:29      DEBUG: Conversion of value '' failed, using default '0'
2023-11-14 09:51:29      DEBUG: Jeedom - read variable daikin.--retiré--.heating_current --> 0
2023-11-14 09:51:29      DEBUG: Starting new HTTP connection (1): 127.0.0.1:80
2023-11-14 09:51:29      DEBUG: http://127.0.0.1:80 "GET /core/api/jeeApi.php?apikey=--retiré--&type=variable&name=daikin.--retiré--.heating_commit HTTP/1.1" 200 0
2023-11-14 09:51:29      DEBUG: Conversion of value '' failed, using default '0'
2023-11-14 09:51:29      DEBUG: Jeedom - read variable daikin.--retiré--.heating_commit --> 0
2023-11-14 09:51:29      DEBUG: --retiré-- - commit_date: 1970-01-01 01:00:00, heating_current: 0, heating_commit: 0
2023-11-14 09:51:29    WARNING: Last date is before yesterday - data is lost
2023-11-14 09:51:29      DEBUG: Current slot: 22
2023-11-14 09:51:29      DEBUG: Last slot: 0
2023-11-14 09:51:29       INFO: --retiré--: heating update 0 + 13 + None
Traceback (most recent call last):
  File "daikin_to_jeedom.py", line 332, in <module>
    values['heating_current'] = values['heating_commit'] + heating_update[1]
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

Furthermore, is it normal to see a date at '1970-01-01 01:00:00' ?
So is this why the data remains at zero ?


Thank you again for your help.
Best regards

**Comment by dricair** [comment]
Ok I will check in more details, it may mean that the data is not exactly the same form. Data which are 0 or 1970... are expected as these are the default values until variable has been written once in Jeedom.

**Comment by dricair** [comment]
It looks like that in your file, data for the current and future slots are None instead of 0. So I added a conversion.

**Comment by L0nhed** [comment]
Dear @dricair ,
It's good !
Thank you a lot !!
Best regards
